version: '3.8'

services:
  nginx-reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      - auth-token-manager
      - test-html-server
    networks:
      - auth-token-network

  auth-token-manager:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app/instance:/app/instance
    networks:
      - auth-token-network

  test-html-server:
    image: nginx:latest
    volumes:
      - ./dummy_nginx/html:/usr/share/nginx/html:ro
      - ./dummy_nginx/conf.d:/etc/nginx/conf.d
    networks:
      - auth-token-network

networks:
  auth-token-network:
    driver: bridge